const gnr = {
    '1.º Destacamento de Ação Conjunto (Lisboa)': 'unt.daclsb@gnr.pt',
    '2.º Destacamento de Ação Conjunto (Porto)': 'unt.dacprt@gnr.pt',
    '2.º Esquadrão Moto': 'ushe.ghe2e@gnr.pt',
    '3.º Esquadrão A Cavalo': 'ushe.ghe3e@gnr.pt',
    '4.º Esquadrão A Cavalo': 'ushe.ghe4e@gnr.pt',
    'Arquivo Histórico GNR': 'cg.sg.dhcg@gnr.pt',
    'Banda de Música e Fanfarra': 'ushe.bm@gnr.pt',
    'Centro Clínico': 'cari.cc@gnr.pt',
    'Centro de Comando e Controlo Operacional (Núcleo)': 'co.ccco@gnr.pt',
    'Centro de Comando e Controlo Operacional': 'co.ccco.soc@gnr.pt',
    'Centro de Coop. Policial e Aduaneira Quintanilha / S. M. Del Pedroso': 'ccpa.quintanilha@gnr.pt',
    'Centro de Cooperação Policial e Aduaneira Valença do Minho / Tuy': 'ccpa.tuy@gnr.pt',
    'Centro de Cooperação Policial e Aduaneira de Castro Marim / Ayamonte': 'ccpa.ctm@gnr.pt',
    'Centro de Ensino e Desbaste de Solípedes': 'ushe.ceds@gnr.pt',
    'Centro de Formação da Figueira da Foz': 'eg.cfff@gnr.pt',
    'Centro de Formação de Portalegre': 'eg.cfp@gnr.pt',
    'Centro de Psicologia e Intervenção Social': 'cari.drh.cpis@gnr.pt',
    'Centro de Reabastecimento': 'cari.uag.creab@gnr.pt',
    'Charanga': 'ushe.charanga@gnr.pt',
    'Comando Geral da Guarda Nacional Republicana': 'gnr@gnr.pt',
    'Comando Operacional': 'co@gnr.pt',
    'Comando Territorial da Guarda': 'ct.grd@gnr.pt',
    'Comando Territorial de Aveiro': 'ct.avr@gnr.pt',
    'Comando Territorial de Beja': 'ct.bja@gnr.pt',
    'Comando Territorial de Braga': 'ct.brg@gnr.pt',
    'Comando Territorial de Bragança': 'ct.bgc@gnr.pt',
    'Comando Territorial de Castelo Branco': 'ct.ctb@gnr.pt',
    'Comando Territorial de Coimbra': 'ct.cbr@gnr.pt',
    'Comando Territorial de Faro': 'ct.far@gnr.pt',
    'Comando Territorial de Leiria': 'ct.lra@gnr.pt',
    'Comando Territorial de Lisboa': 'ct.lsb@gnr.pt',
    'Comando Territorial de Madeira': 'ct.mad@gnr.pt',
    'Comando Territorial de Portalegre': 'ct.ptg@gnr.pt',
    'Comando Territorial de Porto': 'ct.prt@gnr.pt',
    'Comando Territorial de Santarém': 'ct.str@gnr.pt',
    'Comando Territorial de Setúbal': 'ct.stb@gnr.pt',
    'Comando Territorial de Viana do Castelo': 'ct.vct@gnr.pt',
    'Comando Territorial de Vila Real': 'ct.vrl@gnr.pt',
    'Comando Territorial de Viseu': 'ct.vis@gnr.pt',
    'Comando Territorial de Évora': 'ct.evr@gnr.pt',
    'Comando Territorial dos Açores': 'ct.acr@gnr.pt',
    'Comando de Administração de Recursos Internos': 'cari@gnr.pt',
    'Comando de Doutrina e Formação': 'cdf@gnr.pt',
    'Companhia de Intendência': 'cari.uag.compint@gnr.pt',
    'Companhia de Transportes e Manutenção': 'cari.uag.ctransman@gnr.pt',
    'Delegação do Centro Clínico No Porto': 'cari.cc.prt@gnr.pt',
    'Destacamento Territorial da Covilhã': 'ct.ctb.dcvl@gnr.pt',
    'Destacamento Territorial da Horta': 'ct.acr.dhrt@gnr.pt',
    'Destacamento Territorial de Abrantes': 'ct.str.dabt@gnr.pt',
    'Destacamento Territorial de Albufeira': 'ct.far.dabf@gnr.pt',
    'Destacamento Territorial de Alenquer': 'ct.lsb.dalq@gnr.pt',
    'Destacamento Territorial de Aljustrel': 'ct.bja.dajt@gnr.pt',
    'Destacamento Territorial de Almada': 'ct.stb.dalm@gnr.pt',
    'Destacamento Territorial de Almodôvar': 'ct.bja.dadv@gnr.pt',
    'Destacamento Territorial de Amarante': 'ct.prt.damt@gnr.pt',
    'Destacamento Territorial de Anadia': 'ct.avr.dand@gnr.pt',
    'Destacamento Territorial de Angra do Heroísmo': 'ct.acr.dagh@gnr.pt',
    'Destacamento Territorial de Arcos de Valdevez': 'ct.vct.davv@gnr.pt',
    'Destacamento Territorial de Aveiro': 'ct.avr.davr@gnr.pt',
    'Destacamento Territorial de Barcelos': 'ct.brg.dbcl@gnr.pt',
    'Destacamento Territorial de Beja': 'ct.bja.dbja@gnr.pt',
    'Destacamento Territorial de Braga': 'ct.brg.dbrg@gnr.pt',
    'Destacamento Territorial de Bragança': 'ct.bgc.dbgc@gnr.pt',
    'Destacamento Territorial de Caldas da Rainha': 'ct.lra.dclr@gnr.pt',
    'Destacamento Territorial de Cantanhede': 'ct.cbr.dcnt@gnr.pt',
    'Destacamento Territorial de Castelo Branco': 'ct.ctb.dctb@gnr.pt',
    'Destacamento Territorial de Chaves': 'ct.vrl.dchv@gnr.pt',
    'Destacamento Territorial de Coimbra': 'ct.cbr.dcbr@gnr.pt',
    'Destacamento Territorial de Coruche': 'ct.str.dcch@gnr.pt',
    'Destacamento Territorial de Elvas': 'ct.ptg.delv@gnr.pt',
    'Destacamento Territorial de Estremoz': 'ct.evr.detz@gnr.pt',
    'Destacamento Territorial de Faro': 'ct.far.dfar@gnr.pt',
    'Destacamento Territorial de Felgueiras': 'ct.prt.dflg@gnr.pt',
    'Destacamento Territorial de Funchal': 'ct.mad.dfun@gnr.pt',
    'Destacamento Territorial de Fundão': 'ct.ctb.dfnd@gnr.pt',
    'Destacamento Territorial de Gouveia': 'ct.grd.dgva@gnr.pt',
    'Destacamento Territorial de Grândola': 'ct.stb.dgdl@gnr.pt',
    'Destacamento Territorial de Guarda': 'ct.grd.dgrd@gnr.pt',
    'Destacamento Territorial de Guimarães': 'ct.brg.dgmr@gnr.pt',
    'Destacamento Territorial de Idanha-A-Nova': 'ct.ctb.didn@gnr.pt',
    'Destacamento Territorial de Lamego': 'ct.vis.dlmg@gnr.pt',
    'Destacamento Territorial de Leiria': 'ct.lra.dlra@gnr.pt',
    'Destacamento Territorial de Loulé': 'ct.far.dlle@gnr.pt',
    'Destacamento Territorial de Lousã': 'ct.cbr.dlsa@gnr.pt',
    'Destacamento Territorial de Mafra': 'ct.lsb.dmfr@gnr.pt',
    'Destacamento Territorial de Mangualde': 'ct.vis.dmgl@gnr.pt',
    'Destacamento Territorial de Matosinhos': 'ct.prt.dmts@gnr.pt',
    'Destacamento Territorial de Miranda do Douro': 'ct.bgc.dmdr@gnr.pt',
    'Destacamento Territorial de Mirandela': 'ct.bgc.dmdl.ccom@gnr.pt',
    'Destacamento Territorial de Moimenta da Beira': 'ct.vis.dmbr@gnr.pt',
    'Destacamento Territorial de Montemor-O-Novo': 'ct.evr.dmmn@gnr.pt',
    'Destacamento Territorial de Montemor-O-Velho': 'ct.cbr.dmtv@gnr.pt',
    'Destacamento Territorial de Montijo': 'ct.stb.dmtj@gnr.pt',
    'Destacamento Territorial de Moura': 'ct.bja.dmra@gnr.pt',
    'Destacamento Territorial de Nisa': 'ct.ptg.dnis@gnr.pt',
    'Destacamento Territorial de Odemira': 'ct.bja.dodm@gnr.pt',
    'Destacamento Territorial de Oliveira de Azemeis': 'ct.avr.doaz@gnr.pt',
    'Destacamento Territorial de Ovar': 'ct.avr.dovr@gnr.pt',
    'Destacamento Territorial de Palmela': 'ct.stb.dplm@gnr.pt',
    'Destacamento Territorial de Penafiel': 'ct.prt.dpnf@gnr.pt',
    'Destacamento Territorial de Peso da Régua': 'ct.vrl.dprg@gnr.pt',
    'Destacamento Territorial de Pinhel': 'ct.grd.dpnh@gnr.pt',
    'Destacamento Territorial de Pombal': 'ct.lra.dpbl@gnr.pt',
    'Destacamento Territorial de Ponta Delgada': 'ct.acr.dpdl@gnr.pt',
    'Destacamento Territorial de Ponte de Sor': 'ct.ptg.dpsr@gnr.pt',
    'Destacamento Territorial de Portalegre': 'ct.ptg.dptg@gnr.pt',
    'Destacamento Territorial de Portimão': 'ct.far.dptm@gnr.pt',
    'Destacamento Territorial de Póvoa de Lanhoso': 'ct.brg.dpvl@gnr.pt',
    'Destacamento Territorial de Reguengos de Monsaraz': 'ct.evr.drgm@gnr.pt',
    'Destacamento Territorial de Santa Comba Dão': 'ct.vis.dscd@gnr.pt',
    'Destacamento Territorial de Santa Maria da Feira': 'ct.avr.dsmf@gnr.pt',
    'Destacamento Territorial de Santarém': 'ct.str.dstr@gnr.pt',
    'Destacamento Territorial de Santiago do Cacém': 'ct.stb.dstc@gnr.pt',
    'Destacamento Territorial de Santo Tirso': 'ct.prt.dsts@gnr.pt',
    'Destacamento Territorial de Sertã': 'ct.ctb.dsrt@gnr.pt',
    'Destacamento Territorial de Setúbal': 'ct.stb.dstb@gnr.pt',
    'Destacamento Territorial de Silves': 'ct.far.dslv@gnr.pt',
    'Destacamento Territorial de Sintra': 'ct.lsb.dsnt@gnr.pt',
    'Destacamento Territorial de Tavira': 'ct.far.dtvr@gnr.pt',
    'Destacamento Territorial de Tomar': 'ct.str.dtmr@gnr.pt',
    'Destacamento Territorial de Torre de Moncorvo': 'ct.bgc.dtmc.ccom@gnr.pt',
    'Destacamento Territorial de Torres Novas': 'ct.str.dtnv@gnr.pt',
    'Destacamento Territorial de Torres Vedras': 'ct.lsb.dtvd@gnr.pt',
    'Destacamento Territorial de Valença': 'ct.vct.dvln@gnr.pt',
    'Destacamento Territorial de Viana do Castelo': 'ct.vct.dvct@gnr.pt',
    'Destacamento Territorial de Vila Franca de Xira': 'ct.lsb.dvfx@gnr.pt',
    'Destacamento Territorial de Vila Nova de Gaia': 'ct.prt.dvng@gnr.pt',
    'Destacamento Territorial de Vila Real': 'ct.vrl@gnr.pt',
    'Destacamento Territorial de Vilar Formoso': 'ct.grd.dvfm@gnr.pt',
    'Destacamento Territorial de Viseu': 'ct.vis.dvis@gnr.pt',
    'Destacamento Territorial de Águeda': 'ct.avr.dagd@gnr.pt',
    'Destacamento Territorial de Évora': 'ct.evr.devr@gnr.pt',
    'Destacamento de Ação Fiscal de Coimbra': 'uaf.dcbr@gnr.pt',
    'Destacamento de Ação Fiscal de Faro': 'uaf.dfar@nr.pt',
    'Destacamento de Ação Fiscal de Lisboa': 'uaf.dlsb@gnr.pt',
    'Destacamento de Ação Fiscal de Évora': 'uaf.evr@gnr.pt',
    'Destacamento de Ação Fiscal do Porto': 'uaf.dprt@gnr.pt',
    'Destacamento de Controlo Costeiro da Figueira da Foz': 'ucc.dfgf@gnr.pt',
    'Destacamento de Controlo Costeiro de Lisboa': 'ucc.dlsb@gnr.pt',
    'Destacamento de Controlo Costeiro de Matosinhos': 'ucc.dmts@gnr.pt',
    'Destacamento de Controlo Costeiro de Olhão': 'ucc.dolh@gnr.pt',
    'Destacamento de Controlo Costeiro de Sines': 'ucc.dsin@gnr.pt',
    'Destacamento de Intervenção de Aveiro': 'ct.avr.dint@gnr.pt',
    'Destacamento de Intervenção de Beja': 'ct.bja.dint@gnr.pt',
    'Destacamento de Intervenção de Braga': 'ct.brg.dint@gnr.pt',
    'Destacamento de Intervenção de Castelo Branco': 'ct.ctb.dint@gnr.pt',
    'Destacamento de Intervenção de Coimbra': 'ct.cbr.dint@gnr.pt',
    'Destacamento de Intervenção de Faro': 'ct.far.dint@gnr.pt',
    'Destacamento de Intervenção de Leiria': 'ct.lra.dint@gnr.pt',
    'Destacamento de Intervenção de Lisboa': 'ct.lsb.dint@gnr.pt',
    'Destacamento de Intervenção de Portalegre': 'ct.ptg.dint@gnr.pt',
    'Destacamento de Intervenção de Setúbal': 'ct.stb.dint@gnr.pt',
    'Destacamento de Intervenção de Viana do Castelo': 'ct.vct.dint@gnr.pt',
    'Destacamento de Intervenção de Vila Real': 'ct.vrl.dint@gnr.pt',
    'Destacamento de Intervenção de Viseu': 'ct.vis.dint@gnr.pt',
    'Destacamento de Intervenção de Évora': 'ct.evr.dint@gnr.pt',
    'Destacamento de Intervenção do Porto': 'ct.prt.dint@gnr.pt',
    'Destacamento de Pesquisa de Âmbito Nacional da Unidade de Ação Fiscal': 'uaf.dp@gnr.pt',
    'Destacamento de Trânsito da Guarda': 'ct.grd.tgrd@gnr.pt',
    'Destacamento de Trânsito de Aveiro': 'ct.avr.tavr@gnr.pt',
    'Destacamento de Trânsito de Beja': 'ct.bja.tbja@gnr.pt',
    'Destacamento de Trânsito de Braga': 'ct.brg.tbrg@gnr.pt',
    'Destacamento de Trânsito de Bragança': 'ct.bgc.tbgc@gnr.pt',
    'Destacamento de Trânsito de Carcavelos': 'ct.lsb.tccv@gnr.pt',
    'Destacamento de Trânsito de Carregado': 'ct.lsb.tcrg@gnr.pt',
    'Destacamento de Trânsito de Castelo Branco': 'ct.ctb.tctb@gnr.pt',
    'Destacamento de Trânsito de Coimbra': 'ct.cbr.tcbr@gnr.pt',
    'Destacamento de Trânsito de Faro': 'ct.far.tfar@gnr.pt',
    'Destacamento de Trânsito de Lagos': 'ct.far.tlgs@gnr.pt',
    'Destacamento de Trânsito de Penafiel': 'ct.prt.tpnf@gnr.pt',
    'Destacamento de Trânsito de Portalegre': 'ct.ptg.tptg@gnr.pt',
    'Destacamento de Trânsito de Porto': 'ct.prt.tprt@gnr.pt',
    'Destacamento de Trânsito de Santarém': 'ct.str.tstr@gnr.pt',
    'Destacamento de Trânsito de Setúbal': 'ct.stb.tstb@gnr.pt',
    'Destacamento de Trânsito de São João da Madeira': 'ct.avr.tsjm@gnr.pt',
    'Destacamento de Trânsito de Torres Vedras': 'ct.lsb.ttvd@gnr.pt',
    'Destacamento de Trânsito de Viana do Castelo': 'ct.vct.tvct@gnr.pt',
    'Destacamento de Trânsito de Vila Real': 'ct.vrl.tvrl@gnr.pt',
    'Destacamento de Trânsito de Viseu': 'ct.vis.tvis@gnr.pt',
    'Destacamento de Trânsito de Évora': 'ct.evr.tevr@gnr.pt',
    'Destacamento de Vigilância Móvel': 'ucc.dvm@gnr.pt',
    'Direção Sepna': 'co.dsepna@gnr.pt',
    'Direção da Formação': 'cdf.df@gnr.pt',
    'Direção de Comunicações e Sistemas de Informação': 'co.dcsi@gnr.pt',
    'Direção de Doutrina': 'cdf.dd@gnr.pt',
    'Direção de Informações': 'co.di@gnr.pt',
    'Direção de Infraestruturas': 'cari.die@gnr.pt',
    'Direção de Investigação Criminal': 'co.dic@gnr.pt',
    'Direção de Justiça e Disciplina': 'djd@gnr.pt',
    'Direção de Operações': 'co.do@gnr.pt',
    'Direção de Recursos Financeiros': 'cari.drf@gnr.pt',
    'Direção de Recursos Humanos': 'cari.drh@gnr.pt',
    'Direção de Recursos Logísticos': 'cari.drl@gnr.pt',
    'Direção de Saúde e Assistência Na Doença': 'cari.dsad@gnr.pt',
    'Divisão de Assistência Na Doença': 'cari.dsad.dad@gnr.pt',
    'Divisão de Comunicação e Relações Públicas': 'dcrp@gnr.pt',
    'Divisão de Consultadoria Jurídica': 'cg.consultadoria.juridica@gnr.pt',
    'Divisão de História e Cultura': 'cg.sg.dhcg@gnr.pt',
    'Divisão de Medicina Veterinária': 'cari.dsad.dmv@gnr.pt',
    'Divisão de Planeamento Estratégico e Relações Internacionais': 'dperi@gnr.pt',
    'Divisão de Saúde': 'cari.dsad.ds@gnr.pt',
    'Escola da Guarda': 'eg@gnr.pt',
    'Esquadrão Presidencial': 'ushe.ep@gnr.pt',
    'Gabinete do 2.º Comandante Geral': 'cg.gab2cg@gnr.pt',
    'Gabinete do Comandante Geral': 'cg.gabcg@gnr.pt',
    'Gabinete do Comandante Operacional': 'co@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 1.ª Companhia': 'ui.gips.1c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 2.ª Companhia': 'ui.gips.2c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 3.ª Companhia': 'ui.gips.3c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 4.ª Companhia': 'ui.gips.4c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 5.ª Companhia': 'ui.gips.5c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 6.ª Companhia': 'ui.gips.6c@gnr.pt',
    'Grupo Intervenção Proteção Socorro - 7.ª Companhia': 'ui.gips.7c@gnr.pt',
    'Grupo Intervenção Proteção Socorro Subagrupamento Montanha': 'ui.gips.samont@gnr.pt',
    'Grupo de Honras de Estado': 'ushe.ghe@gnr.pt',
    'Grupo de Intervenção Cinotécnico': 'ui.gic@gnr.pt',
    'Grupo de Intervenção de Proteção e Socorro': 'ui.gips@gnr.pt',
    'Grupo de Segurança - 1.ª Companhia': 'ushe.gs.1c@gnr.pt',
    'Grupo de Segurança - 3.ª Companhia': 'ushe.gs.3c@gnr.pt',
    'Grupo de Segurança': 'ushe.gs@gnr.pt',
    'Inspeção da Guarda': 'ig@gnr.pt',
    'Museu da GNR': 'museu@gnr.pt',
    'Posto Fiscal da Banática': 'ct.stb.dalm.fbnt@gnr.pt',
    'Posto Fiscal da Zona Franca da Madeira': 'ct.mad.dfun.fzfm@gnr.pt',
    'Posto Fiscal de Alfragide (Encerrado Em 30Abr13)': 'ct.lsb.dsnt.fafg@gnr.pt',
    'Posto Fiscal de Pedras Rubras': 'ct.prt.dmts.ppdr@gnr.pt',
    'Posto Fiscal do Aeroporto Faro': 'ct.far.dfar.ffar@gnr.pt',
    'Posto Fiscal do Aeroporto de Lisboa': 'ct.lsb.dvfx.fael@gnr.pt',
    'Posto Fiscal do Aeroporto do Funchal': 'ct.mad.dfun.faef@gnr.pt',
    'Posto Fiscal do Ministério das Finanças': 'ct.lsb.dvfx.fmfi@gnr.pt',
    'Posto Territorial Alcains': 'ct.ctb.dctb.palc@gnr.pt',
    'Posto Territorial Arganil': 'ct.cbr.darg.parg@gnr.pt',
    'Posto Territorial da Bemposta': 'ct.str.dabt.pbpt@gnr.pt',
    'Posto Territorial da Charneca de Caparica': 'ct.stb.dalm.pchc@gnr.pt',
    'Posto Territorial da Costa de Caparica': 'ct.stb.dalm.pccp@gnr.pt',
    'Posto Territorial da Covilhã': 'ct.ctb.dcvl.pcvl@gnr.pt',
    'Posto Territorial da Horta (Faial)': 'ct.acr.dhrt.phrt@gnr.pt',
    'Posto Territorial da Praia (Graciosa)': 'ct.acr.dagh.ppra@gnr.pt',
    'Posto Territorial da Praia da Vitória (Terceira)': 'ct.acr.dagh.pprv@gnr.pt',
    'Posto Territorial das Velas (São Jorge)': 'ct.acr.dagh.pvls@gnr.pt',
    'Posto Territorial de Abrantes': 'ct.str.dabt.pabt@gnr.pt',
    'Posto Territorial de Aguiar da Beira': 'ct.grd.dgva.pagb@gnr.pt',
    'Posto Territorial de Alandroal': 'ct.evr.drgm.pald@gnr.pt',
    'Posto Territorial de Albergaria-A-Velha': 'ct.avr.dagd.pabv@gnr.pt',
    'Posto Territorial de Alcanena': 'ct.str.dtnv.pacn@gnr.pt',
    'Posto Territorial de Alcobaça': 'ct.lra.dalb.palb@gnr.pt',
    'Posto Territorial de Alcochete': 'ct.stb.dmtj.palc@gnr.pt',
    'Posto Territorial de Alcoutim': 'ct.far.dtvr.pact@gnr.pt',
    'Posto Territorial de Alcácer do Sal': 'ct.stb.dgdl.pasl@gnr.pt',
    'Posto Territorial de Alcáçovas': 'ct.evr.dmmn.pacv@gnr.pt',
    'Posto Territorial de Alenquer': 'ct.lsb.dalq.palq@gnr.pt',
    'Posto Territorial de Alfarim': 'ct.stb.dstb.pafr@gnr.pt',
    'Posto Territorial de Alfena': 'ct.prt.dsts.pafn@gnr.pt',
    'Posto Territorial de Alfândega da Fé': 'ct.bgc.dtmc.pafe@gnr.pt',
    'Posto Territorial de Alijó': 'ct.vrl.dprg.palj@gnr.pt',
    'Posto Territorial de Aljezur': 'ct.far.dptm.pajz@gnr.pt',
    'Posto Territorial de Aljustrel': 'ct.bja.dajt.pajt@gnr.pt',
    'Posto Territorial de Almancil': 'ct.far.dlle.palc@gnr.pt',
    'Posto Territorial de Almeida': 'ct.grd.dvfm.pald@gnr.pt',
    'Posto Territorial de Almeirim': 'ct.str.dstr.palr@gnr.pt',
    'Posto Territorial de Almodôvar': 'ct.bja.dadv.padv@gnr.pt',
    'Posto Territorial de Alpalhão': 'ct.ptg.dnis.papl@gnr.pt',
    'Posto Territorial de Alpedrinha': 'ct.ctb.dfnd.papd@gnr.pt',
    'Posto Territorial de Alpendurada': 'ct.prt.damt.palp@gnr.pt',
    'Posto Territorial de Alpiarça': 'ct.str.dstr.palp@gnr.pt',
    'Posto Territorial de Alter do Chão': 'ct.ptg.dptg.patc@gnr.pt',
    'Posto Territorial de Alvaiázere': 'ct.lra.dpbl.palv@gnr.pt',
    'Posto Territorial de Alvalade do Sado': 'ct.stb.dstc.pals@gnr.pt',
    'Posto Territorial de Alvito': 'ct.bja.dbja.palv@gnr.pt',
    'Posto Territorial de Amarante': 'ct.prt.damt.pamt@gnr.pt',
    'Posto Territorial de Amareleja': 'ct.bja.dmra.paja@gnr.pt',
    'Posto Territorial de Amares': 'ct.brg.dpvl.pamr@gnr.pt',
    'Posto Territorial de Anadia': 'ct.avr.dand.pand@gnr.pt',
    'Posto Territorial de Ansião': 'ct.lra.dpbl.pans@gnr.pt',
    'Posto Territorial de Ançã': 'ct.cbr.dcnt.panc@gnr.pt',
    'Posto Territorial de Arcos de Valdevez': 'ct.vct.davv.pavv@gnr.pt',
    'Posto Territorial de Arcozelo': 'ct.prt.dvng.parc@gnr.pt',
    'Posto Territorial de Argozelo': 'ct.bgc.dmdr.parz@gnr.pt',
    'Posto Territorial de Armamar': 'ct.vis.dlmg.parm@gnr.pt',
    'Posto Territorial de Armação de Pêra': 'ct.far.dslv.pamp@gnr.pt',
    'Posto Territorial de Arouca': 'ct.avr.doaz.parc@gnr.pt',
    'Posto Territorial de Arraiolos': 'ct.evr.detz.parl@gnr.pt',
    'Posto Territorial de Arrancada do Vouga': 'ct.avr.dagd.parv@gnr.pt',
    'Posto Territorial de Arronches': 'ct.ptg.delv.parc@gnr.pt',
    'Posto Territorial de Arruda dos Vinhos': 'ct.lsb.dvfx.parv@gnr.pt',
    'Posto Territorial de Avanca': 'ct.avr.dovr.pavc@gnr.pt',
    'Posto Territorial de Aveiras': 'ct.lsb.dalq.pavr@gnr.pt',
    'Posto Territorial de Aveiro (Oliveirinha)': 'ct.avr.davr.pavr@gnr.pt',
    'Posto Territorial de Avelal': 'ct.vis.dmgl.pavl@gnr.pt',
    'Posto Territorial de Avintes': 'ct.prt.dvng.pavt@gnr.pt',
    'Posto Territorial de Avis': 'ct.ptg.dpsr.pavs@gnr.pt',
    'Posto Territorial de Azambuja': 'ct.lsb.dalq.pazb@gnr.pt',
    'Posto Territorial de Azaruja': 'ct.evr.devr.pazr@gnr.pt',
    'Posto Territorial de Azeitão': 'ct.stb.dstb.pvna@gnr.pt',
    'Posto Territorial de Azinheira de Barros': 'ct.stb.dgdl.pazb@gnr.pt',
    'Posto Territorial de Baião': 'ct.prt.damt.pbai@gnr.pt',
    'Posto Territorial de Baleizão': 'ct.bja.dbja.pblz@gnr.pt',
    'Posto Territorial de Barcelos': 'ct.brg.dbcl.pbcl@gnr.pt',
    'Posto Territorial de Barrancos': 'ct.bja.dmra.pbrs@gnr.pt',
    'Posto Territorial de Barroselas': 'ct.vct.dvct.pbrs@gnr.pt',
    'Posto Territorial de Batalha': 'ct.lra.dlra.pbtl@gnr.pt',
    'Posto Territorial de Beja': 'ct.bja.dbja.pbja@gnr.pt',
    'Posto Territorial de Belmonte': 'ct.ctb.dcvl.pblm@gnr.pt',
    'Posto Territorial de Benavente': 'ct.str.dcch.pbnv@gnr.pt',
    'Posto Territorial de Bencatel': 'ct.evr.drgm.pbct@gnr.pt',
    'Posto Territorial de Benedita': 'ct.lra.dalb.pbnd@gnr.pt',
    'Posto Territorial de Beringel': 'ct.bja.dbja.pbrg@gnr.pt',
    'Posto Territorial de Bombarral': 'ct.lra.dclr.pbbr@gnr.pt',
    'Posto Territorial de Borba': 'ct.evr.detz.pbrb@gnr.pt',
    'Posto Territorial de Boticas': 'ct.vrl.dchv.pbtc@gnr.pt',
    'Posto Territorial de Braga': 'ct.brg.dbrg.pbrg@gnr.pt',
    'Posto Territorial de Bragança': 'ct.bgc.dbgc.pbgc@gnr.pt',
    'Posto Territorial de Brinches': 'ct.bja.dmra.pbcs@gnr.pt',
    'Posto Territorial de Bucelas': 'ct.lsb.dvfx.pbcl@gnr.pt',
    'Posto Territorial de Bustos': 'ct.avr.dand.pbst@gnr.pt',
    'Posto Territorial de Cabeceiras de Basto': 'ct.brg.dfaf.pcbb@gnr.pt',
    'Posto Territorial de Cabeço de Vide': 'ct.ptg.dptg.pcbv@gnr.pt',
    'Posto Territorial de Cabrela': 'ct.evr.dmmn.pcbl@gnr.pt',
    'Posto Territorial de Cacia': 'ct.avr.davr.pcac@gnr.pt',
    'Posto Territorial de Cadaval': 'ct.lsb.dalq.pcdv@gnr.pt',
    'Posto Territorial de Caldas da Rainha': 'ct.lra.dclr.pclr@gnr.pt',
    'Posto Territorial de Caldas das Taipas': 'ct.brg.dgmr.pcdt@gnr.pt',
    'Posto Territorial de Caminha': 'ct.vct.dvct.pcmn@gnr.pt',
    'Posto Territorial de Campo Maior': 'ct.ptg.delv.pcpm@gnr.pt',
    'Posto Territorial de Campo de Besteiros': 'ct.vis.dscd.pcbt@gnr.pt',
    'Posto Territorial de Canas de Senhorim': 'ct.vis.dmgl.pcns@gnr.pt',
    'Posto Territorial de Canedo': 'ct.avr.dsmf.pcnd@gnr.pt',
    'Posto Territorial de Canelas': 'ct.prt.dvng.pcnl@gnr.pt',
    'Posto Territorial de Canha': 'ct.stb.dplm.pcnh@gnr.pt',
    'Posto Territorial de Cantanhede': 'ct.cbr.dcnt.pcnt@gnr.pt',
    'Posto Territorial de Caramulo': 'ct.vis.dscd.pcrm@gnr.pt',
    'Posto Territorial de Caria': 'ct.ctb.dcvl.pcar@gnr.pt',
    'Posto Territorial de Carrazeda de Ansiães': 'ct.bgc.dmdl.pcrz@gnr.pt',
    'Posto Territorial de Carrazedo de Montenegro': 'ct.vrl.dchv.pczm@gnr.pt',
    'Posto Territorial de Carregal do Sal': 'ct.vis.dscd.pcrs@gnr.pt',
    'Posto Territorial de Cartaxo': 'ct.str.dstr.pctx@gnr.pt',
    'Posto Territorial de Carvalhos': 'ct.prt.dvng.pcrv@gnr.pt',
    'Posto Territorial de Carvoeiro': 'ct.far.dslv.pcrv@gnr.pt',
    'Posto Territorial de Casa Branca': 'ct.ptg.dpsr.pcsb@gnr.pt',
    'Posto Territorial de Castanheira de Pêra': 'ct.lra.dpbl.pctp@gnr.pt',
    'Posto Territorial de Castanheira do Ribatejo': 'ct.lsb.dvfx.pctr@gnr.pt',
    'Posto Territorial de Castelo Branco': 'ct.ctb.dctb.pctb@gnr.pt',
    'Posto Territorial de Castelo de Paiva': 'ct.avr.doaz.pctp@gnr.pt',
    'Posto Territorial de Castelo de Vide': 'ct.ptg.dnis.pctv@gnr.pt',
    'Posto Territorial de Castro Daire': 'ct.vis.dvis.pctd@gnr.pt',
    'Posto Territorial de Castro Marim': 'ct.far.dtvr.pctm@gnr.pt',
    'Posto Territorial de Castro Verde': 'ct.bja.dadv.pctv@gnr.pt',
    'Posto Territorial de Cebolais de Cima': 'ct.ctb.dctb.pcbc@gnr.pt',
    'Posto Territorial de Celorico da Beira': 'ct.grd.dgva.pclb@gnr.pt',
    'Posto Territorial de Celorico de Basto': 'ct.brg.dfaf.pclb@gnr.pt',
    'Posto Territorial de Cercal': 'ct.stb.dstc.pcrc@gnr.pt',
    'Posto Territorial de Cernache do Bonjardim': 'ct.ctb.dsrt.pcnb@gnr.pt',
    'Posto Territorial de Cerva': 'ct.vrl.dvrl.pcrv@gnr.pt',
    'Posto Territorial de Cesar': 'ct.avr.doaz.pcsr@gnr.pt',
    'Posto Territorial de Chamusca': 'ct.str.dtnv.pchm@gnr.pt',
    'Posto Territorial de Chaves': 'ct.vrl.dchv.pchv@gnr.pt',
    'Posto Territorial de Cinfães': 'ct.vis.dlmg.pcin@gnr.pt',
    'Posto Territorial de Colares': 'ct.lsb.dsnt.pclr@gnr.pt',
    'Posto Territorial de Colos': 'ct.bja.dodm.pcls@gnr.pt',
    'Posto Territorial de Comporta': 'ct.stb.dgdl.pcmp@gnr.pt',
    'Posto Territorial de Condeixa-A-Nova': 'ct.cbr.dcbr.pcdn@gnr.pt',
    'Posto Territorial de Constância': 'ct.str.dabt.pcst@gnr.pt',
    'Posto Territorial de Coruche': 'ct.str.dcch.pcch@gnr.pt',
    'Posto Territorial de Couço': 'ct.str.dcch.pcoc@gnr.pt',
    'Posto Territorial de Crato': 'ct.ptg.dptg.pcrt@gnr.pt',
    'Posto Territorial de Cuba': 'ct.bja.dbja.pcub@gnr.pt',
    'Posto Territorial de Cucujães': 'ct.avr.doaz.pccj@gnr.pt',
    'Posto Territorial de Elvas': 'ct.ptg.delv.pelv@gnr.pt',
    'Posto Territorial de Ericeira': 'ct.lsb.dmfr.perc@gnr.pt',
    'Posto Territorial de Ermidas do Sado': 'ct.stb.dstc.pers@gnr.pt',
    'Posto Territorial de Ervidel': 'ct.bja.dajt.pevd@gnr.pt',
    'Posto Territorial de Escoural': 'ct.evr.dmmn.pecr@gnr.pt',
    'Posto Territorial de Esmoriz': 'ct.avr.dovr.pesm@gnr.pt',
    'Posto Territorial de Esposende': 'ct.brg.dbcl.pesp@gnr.pt',
    'Posto Territorial de Estarreja': 'ct.avr.dovr.petr@gnr.pt',
    'Posto Territorial de Estremoz': 'ct.evr.detz.petz@gnr.pt',
    'Posto Territorial de Faro': 'ct.far.dfar.pfar@gnr.pt',
    'Posto Territorial de Felgueiras': 'ct.prt.dflg.pflg@gnr.pt',
    'Posto Territorial de Fernão Ferro': 'ct.stb.dalm.pfrf@gnr.pt',
    'Posto Territorial de Ferreira do Alentejo': 'ct.bja.dajt.pfra@gnr.pt',
    'Posto Territorial de Ferreira do Zêzere': 'ct.str.dtmr.pfrz@gnr.pt',
    'Posto Territorial de Figueira de Castelo Rodrigo': 'ct.grd.dvfm.pfcr@gnr.pt',
    'Posto Territorial de Figueiró dos Vinhos': 'ct.lra.dpbl.pfgv@gnr.pt',
    'Posto Territorial de Fornos de Algodres': 'ct.grd.dgva.pfna@gnr.pt',
    'Posto Territorial de Freamunde': 'ct.prt.dflg.pfrm@gnr.pt',
    'Posto Territorial de Freixedas': 'ct.grd.dpnh.pfxd@gnr.pt',
    'Posto Territorial de Freixo de Espada À Cinta': 'ct.bgc.dtmc.pfec@gnr.pt',
    'Posto Territorial de Freixo de Numão': 'ct.grd.dpnh.pfxn@gnr.pt',
    'Posto Territorial de Fronteira': 'ct.ptg.dptg.pfrt@gnr.pt',
    'Posto Territorial de Fundão': 'ct.ctb.dfnd.pfnd@gnr.pt',
    'Posto Territorial de Fátima': 'ct.str.dtmr.pftm@gnr.pt',
    'Posto Territorial de Fânzeres': 'ct.prt.dvng.pfnz@gnr.pt',
    'Posto Territorial de Gafanha da Nazaré': 'ct.avr.davr.pgfn@gnr.pt',
    'Posto Territorial de Galveias': 'ct.ptg.dpsr.pglv@gnr.pt',
    'Posto Territorial de Garvão': 'ct.bja.dajt.pgrv@gnr.pt',
    'Posto Territorial de Gavião': 'ct.ptg.dnis.pgav@gnr.pt',
    'Posto Territorial de Gerês': 'ct.brg.dpvl.pgrs@gnr.pt',
    'Posto Territorial de Golegã': 'ct.str.dtnv.pglg@gnr.pt',
    'Posto Territorial de Gonçalo': 'ct.grd.dgrd.pgnl@gnr.pt',
    'Posto Territorial de Gouveia': 'ct.grd.dgva.pgva@gnr.pt',
    'Posto Territorial de Granja': 'ct.evr.drgm.grj@gnr.pt',
    'Posto Territorial de Grândola': 'ct.stb.dgdl.pgdl@gnr.pt',
    'Posto Territorial de Guarda': 'ct.grd.dgrd.pgrd@gnr.pt',
    'Posto Territorial de Guia': 'ct.lra.dpbl.pgui@gnr.pt',
    'Posto Territorial de Guimarães (S. Torcato)': 'ct.brg.dgmr.pgmr@gnr.pt',
    'Posto Territorial de Gáfete': 'ct.ptg.dptg.pgft@gnr.pt',
    'Posto Territorial de Góis': 'ct.cbr.darg.pgois@gnr.pt',
    'Posto Territorial de Idanha-A-Nova': 'ct.ctb.didn.pidn@gnr.pt',
    'Posto Territorial de Izeda': 'ct.bgc.dbgc.pizd@gnr.pt',
    'Posto Territorial de Joane': 'ct.brg.dvnf.pjoa@gnr.pt',
    'Posto Territorial de Ladoeiro': 'ct.ctb.didn.pldr@gnr.pt',
    'Posto Territorial de Lagoa': 'ct.far.dslv.plag@gnr.pt',
    'Posto Territorial de Lagos': 'ct.far.dptm.plgs@gnr.pt',
    'Posto Territorial de Lamego': 'ct.vis.dlmg.plmg@gnr.pt',
    'Posto Territorial de Lanheses': 'ct.vct.dvct.plnh@gnr.pt',
    'Posto Territorial de Lavre': 'ct.evr.dmmn.plvr@gnr.pt',
    'Posto Territorial de Lebução': 'ct.vrl.dchv.plbc@gnr.pt',
    'Posto Territorial de Leiria': 'ct.lra.dlra.plra@gnr.pt',
    'Posto Territorial de Lever': 'ct.prt.dvng.plvr@gnr.pt',
    'Posto Territorial de Livramento': 'ct.lsb.dmfr.plvm@gnr.pt',
    'Posto Territorial de Lordelo': 'ct.brg.dgmr.plrd@gnr.pt',
    'Posto Territorial de Lordelo': 'ct.prt.dpnf.plrd@gnr.pt',
    'Posto Territorial de Loriga': 'ct.grd.dsei.plrg@gnr.pt',
    'Posto Territorial de Loulé': 'ct.far.dlle.plle@gnr.pt',
    'Posto Territorial de Lourinhã': 'ct.lsb.dtvd.plrn@gnr.pt',
    'Posto Territorial de Lourosa': 'ct.avr.dsmf.plrs@gnr.pt',
    'Posto Territorial de Lousada': 'ct.prt.dflg.plsd@gnr.pt',
    'Posto Territorial de Lousã': 'ct.cbr.dlsa.plsa@gnr.pt',
    'Posto Territorial de Macedo de Cavaleiros': 'ct.bgc.dbgc.pmcc@gnr.pt',
    'Posto Territorial de Mafra': 'ct.lsb.dmfr.pmfr@gnr.pt',
    'Posto Territorial de Maia': 'ct.prt.dmts.pmai@gnr.pt',
    'Posto Territorial de Maiorca': 'ct.cbr.dmtv.pmrc@gnr.pt',
    'Posto Territorial de Malpica do Tejo': 'ct.ctb.dctb.pmpt@gnr.pt',
    'Posto Territorial de Malveira': 'ct.lsb.dmfr.pmlv@gnr.pt',
    'Posto Territorial de Mangualde': 'ct.vis.dmgl.pmgl@gnr.pt',
    'Posto Territorial de Manteigas': 'ct.grd.dsei.pmtg@gnr.pt',
    'Posto Territorial de Marco de Canaveses': 'ct.prt.damt.pmcn@gnr.pt',
    'Posto Territorial de Marinhais': 'ct.str.dcch.pmrn@gnr.pt',
    'Posto Territorial de Martinlongo': 'ct.far.dtvr.pmrl@gnr.pt',
    'Posto Territorial de Marvão': 'ct.ptg.dnis.pmrv@gnr.pt',
    'Posto Territorial de Mata': 'ct.ctb.dctb.pmat@gnr.pt',
    'Posto Territorial de Matosinhos': 'ct.prt.dmts.pmts@gnr.pt',
    'Posto Territorial de Mação': 'ct.str.dabt.pmac@gnr.pt',
    'Posto Territorial de Mealhada': 'ct.avr.dand.pmlh@gnr.pt',
    'Posto Territorial de Medas': 'ct.prt.dvng.pmds@gnr.pt',
    'Posto Territorial de Melgaço': 'ct.vct.dvln.pmlg@gnr.pt',
    'Posto Territorial de Merceana': 'ct.lsb.dalq.pmrc@gnr.pt',
    'Posto Territorial de Mesão Frio': 'ct.vrl.dprg.pmsf@gnr.pt',
    'Posto Territorial de Mina de São Domingos': 'ct.bja.dadv.pmsd@gnr.pt',
    'Posto Territorial de Mira de Aire': 'ct.lra.dlra.pmrd@gnr.pt',
    'Posto Territorial de Mira': 'ct.cbr.dcnt.pmir@gnr.pt',
    'Posto Territorial de Miranda do Corvo': 'ct.cbr.dlsa.pmrc@gnr.pt',
    'Posto Territorial de Miranda do Douro': 'ct.bgc.dmdr.pmdr@gnr.pt',
    'Posto Territorial de Mirandela': 'ct.bgc.dmdl.pmdl@gnr.pt',
    'Posto Territorial de Miuzela': 'ct.grd.dvfm.pmzl@gnr.pt',
    'Posto Territorial de Mogadouro': 'ct.bgc.dmdr.pmgd@gnr.pt',
    'Posto Territorial de Moimenta da Beira': 'ct.vis.dmbr.pmbr@gnr.pt',
    'Posto Territorial de Moita de Ferreiros': 'ct.lsb.dtvd.pmtf@gnr.pt',
    'Posto Territorial de Moita': 'ct.stb.dmtj.pmoi@gnr.pt',
    'Posto Territorial de Monchique': 'ct.far.dptm.pmcq@gnr.pt',
    'Posto Territorial de Mondim de Basto': 'ct.vrl.dvrl.pmdb@gnr.pt',
    'Posto Territorial de Monforte': 'ct.ptg.delv.pmnf@gnr.pt',
    'Posto Territorial de Monsanto': 'ct.ctb.didn.pmst@gnr.pt',
    'Posto Territorial de Montalegre': 'ct.vrl.dchv.pmnt@gnr.pt',
    'Posto Territorial de Montargil': 'ct.ptg.dpsr.pmtg@gnr.pt',
    'Posto Territorial de Monte Real': 'ct.lra.dlra.pmtr@gnr.pt',
    'Posto Territorial de Monte Redondo': 'ct.lra.dlra.pmrdn@gnr.pt',
    'Posto Territorial de Montemor-O-Novo': 'ct.evr.dmmn.pmmn@gnr.pt',
    'Posto Territorial de Montemor-O-Velho': 'ct.cbr.dmtv.pmtv@gnr.pt',
    'Posto Territorial de Montijo': 'ct.stb.dmtj.pmtj@gnr.pt',
    'Posto Territorial de Monção': 'ct.vct.dvln.pmnc@gnr.pt',
    'Posto Territorial de Mora': 'ct.evr.detz.pmor@gnr.pt',
    'Posto Territorial de Morais': 'ct.bgc.dbgc.pmrs@gnr.pt',
    'Posto Territorial de Mortágua': 'ct.vis.dscd.pmrt@gnr.pt',
    'Posto Territorial de Moura': 'ct.bja.dmra.pmra@gnr.pt',
    'Posto Territorial de Mourão': 'ct.evr.drgm.pmou@gnr.pt',
    'Posto Territorial de Murtosa': 'ct.avr.dovr.pmrt@gnr.pt',
    'Posto Territorial de Murça': 'ct.vrl.dvrl.pmrc@gnr.pt',
    'Posto Territorial de Mértola': 'ct.bja.dadv.pmrt@gnr.pt',
    'Posto Territorial de Mêda': 'ct.grd.dpnh.pmed@gnr.pt',
    'Posto Territorial de Nelas': 'ct.vis.dmgl.pnel@gnr.pt',
    'Posto Territorial de Nisa': 'ct.ptg.dnis.pnis@gnr.pt',
    'Posto Territorial de Odeceixe': 'ct.far.dptm.podc@gnr.pt',
    'Posto Territorial de Odemira': 'ct.bja.dodm.podm@gnr.pt',
    'Posto Territorial de Oleiros': 'ct.ctb.dsrt.polr@gnr.pt',
    'Posto Territorial de Olhos de Água': 'ct.far.dabf.poda@gnr.pt',
    'Posto Territorial de Olhão': 'ct.far.dfar.polh@gnr.pt',
    'Posto Territorial de Oliveira de Azemeis': 'ct.avr.doaz.poaz@gnr.pt',
    'Posto Territorial de Oliveira de Frades': 'ct.vis.dvis.povf@gnr.pt',
    'Posto Territorial de Oliveira do Bairro': 'ct.avr.dand.polv@gnr.pt',
    'Posto Territorial de Oliveira do Hospital': 'ct.cbr.darg.povh@gnr.pt',
    'Posto Territorial de Ourique': 'ct.bja.dajt.porq@gnr.pt',
    'Posto Territorial de Ourém': 'ct.str.dtmr.pour@gnr.pt',
    'Posto Territorial de Ovar': 'ct.avr.dovr.povr@gnr.pt',
    'Posto Territorial de Paderne': 'ct.far.dabf.ppdr@gnr.pt',
    'Posto Territorial de Paio Pires': 'ct.stb.dalm.pppr@gnr.pt',
    'Posto Territorial de Paião': 'ct.cbr.dmtv.ppai@gnr.pt',
    'Posto Territorial de Palmela': 'ct.stb.dplm.pplm@gnr.pt',
    'Posto Territorial de Pampilhosa da Serra': 'ct.cbr.darg.ppms@gnr.pt',
    'Posto Territorial de Paranhos da Beira': 'ct.grd.dsei.pprb@gnr.pt',
    'Posto Territorial de Paredes de Coura': 'ct.vct.davv.ppdc@gnr.pt',
    'Posto Territorial de Paredes': 'ct.prt.dpnf.pprd@gnr.pt',
    'Posto Territorial de Pataias': 'ct.lra.dalb.ppat@gnr.pt',
    'Posto Territorial de Paul': 'ct.ctb.dcvl.ppaul@gnr.pt',
    'Posto Territorial de Pavia': 'ct.evr.detz.ppav@gnr.pt',
    'Posto Territorial de Paço de Sousa': 'ct.prt.dpnf.ppcs@gnr.pt',
    'Posto Territorial de Paços de Ferreira': 'ct.prt.dflg.ppcf@gnr.pt',
    'Posto Territorial de Pedras Salgadas': 'ct.vrl.dvrl.ppds@gnr.pt',
    'Posto Territorial de Pedrógão Grande': 'ct.lra.dpbl.ppdg@gnr.pt',
    'Posto Territorial de Penacova': 'ct.cbr.dcbr.ppnc@gnr.pt',
    'Posto Territorial de Penafiel': 'ct.prt.dpnf.ppnf@gnr.pt',
    'Posto Territorial de Penalva do Castelo': 'ct.vis.dmgl.ppnc@gnr.pt',
    'Posto Territorial de Penamacor': 'ct.ctb.dfnd.ppnm@gnr.pt',
    'Posto Territorial de Penedono': 'ct.vis.dmbr.ppnd@gnr.pt',
    'Posto Territorial de Penela': 'ct.cbr.dlsa.ppnl@gnr.pt',
    'Posto Territorial de Peniche': 'ct.lra.dclr.ppnc@gnr.pt',
    'Posto Territorial de Pernes': 'ct.str.dstr.pprn@gnr.pt',
    'Posto Territorial de Peso da Régua': 'ct.vrl.dprg.pprg@gnr.pt',
    'Posto Territorial de Pias': 'ct.bja.dmra.ppas@gnr.pt',
    'Posto Territorial de Pinhal Novo': 'ct.stb.dplm.ppnn@gnr.pt',
    'Posto Territorial de Pinhel': 'ct.grd.dpnh.ppnh@gnr.pt',
    'Posto Territorial de Pinhão': 'ct.vrl.dprg.ppnh@gnr.pt',
    'Posto Territorial de Pinzio': 'ct.grd.dgrd.ppnz@gnr.pt',
    'Posto Territorial de Poceirão': 'ct.stb.dplm.ppcr@gnr.pt',
    'Posto Territorial de Pombal': 'ct.lra.dpbl.ppbl@gnr.pt',
    'Posto Territorial de Ponta Delgada (São Miguel)': 'ct.acr.dpdl.ppdl@gnr.pt',
    'Posto Territorial de Ponte da Barca': 'ct.vct.davv.ppnb@gnr.pt',
    'Posto Territorial de Ponte de Lima': 'ct.vct.davv.ppnl@gnr.pt',
    'Posto Territorial de Ponte de Sor': 'ct.ptg.dpsr.psr@gnr.pt',
    'Posto Territorial de Portalegre': 'ct.ptg.dptg.pptg@gnr.pt',
    'Posto Territorial de Portel': 'ct.evr.devr.pprt@gnr.pt',
    'Posto Territorial de Portimão': 'ct.far.dptm.pptm@gnr.pt',
    'Posto Territorial de Porto Santo': 'ct.mad.dfun.ppst@gnr.pt',
    'Posto Territorial de Porto de Mós': 'ct.lra.dlra.ppdm@gnr.pt',
    'Posto Territorial de Prado': 'ct.brg.dbrg.pprd@gnr.pt',
    'Posto Territorial de Praia de Mira': 'ct.cbr.dcnt.pprm@gnr.pt',
    'Posto Territorial de Praia de Quiaios': 'ct.cbr.dmtv.pqui@gnr.pt',
    'Posto Territorial de Proença-A-Nova': 'ct.ctb.dsrt.pprn@gnr.pt',
    'Posto Territorial de Pêro Pinheiro': 'ct.lsb.dsnt.pprp@gnr.pt',
    'Posto Territorial de Póvoa de Lanhoso': 'ct.brg.dpvl.ppvl@gnr.pt',
    'Posto Territorial de Póvoa de Varzim': 'ct.prt.dmts.ppvz@gnr.pt',
    'Posto Territorial de Quinta do Conde': 'ct.stb.dstb.pqdc@gnr.pt',
    'Posto Territorial de Rebordelo': 'ct.bgc.dbgc.prbd@gnr.pt',
    'Posto Territorial de Redondo': 'ct.evr.devr.prdd@gnr.pt',
    'Posto Territorial de Reguengos de Monsaraz': 'ct.evr.drgm.prgm@gnr.pt',
    'Posto Territorial de Resende': 'ct.vis.dlmg.prsd@gnr.pt',
    'Posto Territorial de Riba de Ave': 'ct.brg.dvnf.prda@gnr.pt',
    'Posto Territorial de Ribeira de Pena': 'ct.vrl.dvrl.prbp@gnr.pt',
    'Posto Territorial de Rio Maior': 'ct.str.dstr.prmr@gnr.pt',
    'Posto Territorial de Rosmaninhal': 'ct.ctb.didn.prsm@gnr.pt',
    'Posto Territorial de Rossas': 'ct.brg.dpvl.prss@gnr.pt',
    'Posto Territorial de Ruílhe': 'ct.brg.dbrg.prlh@gnr.pt',
    'Posto Territorial de Sabrosa': 'ct.vrl.dprg.psbr@gnr.pt',
    'Posto Territorial de Sabugal': 'ct.grd.dgrd.psbg@gnr.pt',
    'Posto Territorial de Sabóia': 'ct.bja.dodm.psba@gnr.pt',
    'Posto Territorial de Safara': 'ct.bja.dmra.psfa@gnr.pt',
    'Posto Territorial de Salir': 'ct.far.dlle.pslr@gnr.pt',
    'Posto Territorial de Salvada': 'ct.bja.dbja.pslv@gnr.pt',
    'Posto Territorial de Salvaterra de Magos': 'ct.str.dcch.psmg@gnr.pt',
    'Posto Territorial de Sameiro': 'ct.brg.dbrg.psmr@gnr.pt',
    'Posto Territorial de Samora Correia': 'ct.str.dcch.psmc@gnr.pt',
    'Posto Territorial de Sangalhos': 'ct.avr.dand.psng@gnr.pt',
    'Posto Territorial de Santa Comba Dão': 'ct.vis.dscd.pscd@gnr.pt',
    'Posto Territorial de Santa Cruz das Flores': 'ct.acr.dhrt.pscf@gnr.pt',
    'Posto Territorial de Santa Cruz': 'ct.lsb.dtvd.pstc@gnr.pt',
    'Posto Territorial de Santa Eulália': 'ct.ptg.delv.pste@gnr.pt',
    'Posto Territorial de Santa Maria da Feira': 'ct.avr.dsmf.psmf@gnr.pt',
    'Posto Territorial de Santa Maria de Lamas': 'ct.avr.dsmf.psml@gnr.pt',
    'Posto Territorial de Santa Marta de Penaguião': 'ct.vrl.dprg.psmp@gnr.pt',
    'Posto Territorial de Santarém': 'ct.str.dstr.pastr@gnr.pt',
    'Posto Territorial de Santiago Maior': 'ct.evr.drgm.psrm@gnr.pt',
    'Posto Territorial de Santiago do Cacém': 'ct.stb.dstc.pstc@gnr.pt',
    'Posto Territorial de Santo Aleixo da Restauração': 'ct.bja.dmra.psar@gnr.pt',
    'Posto Territorial de Santo André': 'ct.stb.dstc.psta@gnr.pt',
    'Posto Territorial de Santo António da Charneca': 'ct.stb.dmtj.psac@gnr.pt',
    'Posto Territorial de Santo António das Areias': 'ct.ptg.dnis.psaa@gnr.pt',
    'Posto Territorial de Santo Tirso': 'ct.prt.dsts.psts@gnr.pt',
    'Posto Territorial de Sardoal': 'ct.str.dabt.psrd@gnr.pt',
    'Posto Territorial de Seia': 'ct.grd.dsei.psei@gnr.pt',
    'Posto Territorial de Sendim': 'ct.bgc.dmdr.psnd@gnr.pt',
    'Posto Territorial de Sernancelhe': 'ct.vis.dmbr.psnc@gnr.pt',
    'Posto Territorial de Serpa': 'ct.bja.dmra.psrp@gnr.pt',
    'Posto Territorial de Sertã': 'ct.ctb.dsrt.psrt@gnr.pt',
    'Posto Territorial de Sesimbra': 'ct.stb.dstb.pssb@gnr.pt',
    'Posto Territorial de Setúbal': 'ct.stb.dstb.pstb@gnr.pt',
    'Posto Territorial de Sever do Vouga': 'ct.avr.dagd.psvv@gnr.pt',
    'Posto Territorial de Silvares': 'ct.ctb.dfnd.psvr@gnr.pt',
    'Posto Territorial de Silves': 'ct.far.dslv.pslv@gnr.pt',
    'Posto Territorial de Sines': 'ct.stb.dstc.psin@gnr.pt',
    'Posto Territorial de Soalheira': 'ct.ctb.dfnd.pslr@gnr.pt',
    'Posto Territorial de Sobral da Adiça': 'ct.bja.dmra.psba@gnr.pt',
    'Posto Territorial de Sobral de Monte Agraço': 'ct.lsb.dtvd.psma@gnr.pt',
    'Posto Territorial de Soito': 'ct.grd.dvfm.psot@gnr.pt',
    'Posto Territorial de Soure': 'ct.cbr.dmtv.psor@gnr.pt',
    'Posto Territorial de Sousel': 'ct.ptg.dpsr.pssl@gnr.pt',
    'Posto Territorial de Souselas': 'ct.cbr.dcbr.pssl@gnr.pt',
    'Posto Territorial de Souselo': 'ct.vis.dlmg.pssl@gnr.pt',
    'Posto Territorial de Sátão': 'ct.vis.dmgl.psat@gnr.pt',
    'Posto Territorial de São Bartolomeu de Messines': 'ct.far.dslv.psbm@gnr.pt',
    'Posto Territorial de São Brás de Alportel': 'ct.far.dfar.psba@gnr.pt',
    'Posto Territorial de São Cristóvão': 'ct.evr.dmmn.psct@gnr.pt',
    'Posto Territorial de São João da Pesqueira': 'ct.vis.dmbr.psjp@gnr.pt',
    'Posto Territorial de São Julião do Freixo': 'ct.vct.davv.psjf@gnr.pt',
    'Posto Territorial de São Julião do Tojal': 'ct.lsb.dvfx.psjt@gnr.pt',
    'Posto Territorial de São Luís': 'ct.bja.dodm.psls@gnr.pt',
    'Posto Territorial de São Manços': 'ct.evr.devr.pmnc@gnr.pt',
    'Posto Territorial de São Martinho do Porto': 'ct.lra.dalb.psmp@gnr.pt',
    'Posto Territorial de São Miguel de Machede': 'ct.evr.devr.psmm@gnr.pt',
    'Posto Territorial de São Pedro de Moel': 'ct.lra.dlra.pspm@gnr.pt',
    'Posto Territorial de São Pedro do Sul': 'ct.vis.dvis.psps@gnr.pt',
    'Posto Territorial de São Romão': 'ct.evr.drgm.psrm@gnr.pt',
    'Posto Territorial de São Roque do Pico (Pico)': 'ct.acr.dhrt.psrp@gnr.pt',
    'Posto Territorial de São Teotónio': 'ct.bja.dodm.pstt@gnr.pt',
    'Posto Territorial de São Vicente da Beira': 'ct.ctb.dctb.psvb@gnr.pt',
    'Posto Territorial de São Vicente': 'ct.mad.dfun.psvc@gnr.pt',
    'Posto Territorial de São Vicente': 'ct.prt.dpnf.psvc@gnr.pt',
    'Posto Territorial de Tabuaço': 'ct.vis.dmbr.ptbc@gnr.pt',
    'Posto Territorial de Tangil': 'ct.vct.dvln.ptng@gnr.pt',
    'Posto Territorial de Tarouca': 'ct.vis.dlmg.ptrc@gnr.pt',
    'Posto Territorial de Taveiro': 'ct.cbr.dcbr.ptvr@gnr.pt',
    'Posto Territorial de Tavira': 'ct.far.dtvr.ptvr@gnr.pt',
    'Posto Territorial de Teixoso': 'ct.ctb.dcvl.ptxs@gnr.pt',
    'Posto Territorial de Telheiro': 'ct.evr.drgm.ptlr@gnr.pt',
    'Posto Territorial de Termas de Monfortinho': 'ct.ctb.didn.pmft@gnr.pt',
    'Posto Territorial de Terras de Bouro': 'ct.brg.dpvl.ptrb@gnr.pt',
    'Posto Territorial de Tinalhas': 'ct.ctb.dctb.ptnl@gnr.pt',
    'Posto Territorial de Tocha': 'ct.cbr.dcnt.ptch@gnr.pt',
    'Posto Territorial de Tomar': 'ct.str.dtmr.ptmr@gnr.pt',
    'Posto Territorial de Tondela': 'ct.vis.dscd.ptnd@gnr.pt',
    'Posto Territorial de Torre de Dona Chama': 'ct.bgc.dmdl.ptrc@gnr.pt',
    'Posto Territorial de Torre de Moncorvo': 'ct.bgc.dtmc.ptmc@gnr.pt',
    'Posto Territorial de Torres Novas': 'ct.str.dtnv.ptnv@gnr.pt',
    'Posto Territorial de Torres Vedras': 'ct.lsb.dtvd.ptvd@gnr.pt',
    'Posto Territorial de Torrão': 'ct.stb.dgdl.ptrr@gnr.pt',
    'Posto Territorial de Tortosendo': 'ct.ctb.dcvl.ptts@gnr.pt',
    'Posto Territorial de Trafaria': 'ct.stb.dalm.ptrf@gnr.pt',
    'Posto Territorial de Tramagal': 'ct.str.dabt.ptmg@gnr.pt',
    'Posto Territorial de Trancoso': 'ct.grd.dpnh.ptrn@gnr.pt',
    'Posto Territorial de Trofa': 'ct.prt.dsts.ptrf@gnr.pt',
    'Posto Territorial de Tróia': 'ct.stb.dgdl.ptro@gnr.pt',
    'Posto Territorial de Tábua': 'ct.cbr.darg.ptab@gnr.pt',
    'Posto Territorial de Unhais da Serra': 'ct.ctb.dcvl.puns@gnr.pt',
    'Posto Territorial de Vagos': 'ct.avr.davr.pvgs@gnr.pt',
    'Posto Territorial de Valado dos Frades': 'ct.lra.dalb.pvlf@gnr.pt',
    'Posto Territorial de Vale de Cambra': 'ct.avr.doaz.pvlc@gnr.pt',
    'Posto Territorial de Valença': 'ct.vct.dvln.pvln@gnr.pt',
    'Posto Territorial de Valongo': 'ct.prt.dsts.pvlg@gnr.pt',
    'Posto Territorial de Valpaços': 'ct.vrl.dchv.pvlp@gnr.pt',
    'Posto Territorial de Veiros': 'ct.evr.detz.pvrs@gnr.pt',
    'Posto Territorial de Venda Nova': 'ct.vrl.dchv.pvdn@gnr.pt',
    'Posto Territorial de Vendas Novas': 'ct.evr.dmmn.pvdn@gnr.pt',
    'Posto Territorial de Vialonga': 'ct.lsb.dvfx.pvlg@gnr.pt',
    'Posto Territorial de Viana do Alentejo': 'ct.evr.dmmn.pvna@gnr.pt',
    'Posto Territorial de Viana do Castelo': 'ct.vct.dvct.pvct@gnr.pt',
    'Posto Territorial de Vidago': 'ct.vrl.dchv.pvdg@gnr.pt',
    'Posto Territorial de Vidigueira': 'ct.bja.dbja.pvdg@gnr.pt',
    'Posto Territorial de Vieira de Leiria': 'ct.lra.dlra.pvlr@gnr.pt',
    'Posto Territorial de Vieira do Minho': 'ct.brg.dpvl.pvrm@gnr.pt',
    'Posto Territorial de Vila Alva': 'ct.bja.dbja.pcub@gnr.pt',
    'Posto Territorial de Vila Boim': 'ct.ptg.delv.pvlb@gnr.pt',
    'Posto Territorial de Vila Cova de Lixa': 'ct.prt.dflg.pvcl@gnr.pt',
    'Posto Territorial de Vila Flor': 'ct.bgc.dmdl.pvlf@gnr.pt',
    'Posto Territorial de Vila Franca das Naves': 'ct.grd.dpnh.pvfn@gnr.pt',
    'Posto Territorial de Vila Meã': 'ct.prt.damt.pvlm@gnr.pt',
    'Posto Territorial de Vila Nova Famalicão': 'ct.brg.dvnf.pvnf@gnr.pt',
    'Posto Territorial de Vila Nova da Barquinha': 'ct.str.dtnv.pvnb@gnr.pt',
    'Posto Territorial de Vila Nova de Cerveira': 'ct.vct.dvln.pvnc@gnr.pt',
    'Posto Territorial de Vila Nova de Foz Côa': 'ct.grd.dpnh.pvnf@gnr.pt',
    'Posto Territorial de Vila Nova de Milfontes': 'ct.bja.dodm.pvnm@gnr.pt',
    'Posto Territorial de Vila Nova de Paiva': 'ct.vis.dmbr.pvnp@gnr.pt',
    'Posto Territorial de Vila Nova de Poiares': 'ct.cbr.dlsa.pvnp@gnr.pt',
    'Posto Territorial de Vila Nova de São Bento': 'ct.bja.dmra.pvnb@gnr.pt',
    'Posto Territorial de Vila Nova de Tazem': 'ct.grd.dgva.pvnt@gnr.pt',
    'Posto Territorial de Vila Pouca de Aguiar': 'ct.vrl.dvrl.pvpa@gnr.pt',
    'Posto Territorial de Vila Praia de Âncora': 'ct.vct.dvct.pvpa@gnr.pt',
    'Posto Territorial de Vila Real de Santo António': 'ct.far.dtvr.pvra@gnr.pt',
    'Posto Territorial de Vila Real': 'ct.vrl.dvrl.pvrl@gnr.pt',
    'Posto Territorial de Vila Velha de Ródão': 'ct.ctb.dctb.pvvr@gnr.pt',
    'Posto Territorial de Vila Verde de Ficalho': 'ct.bja.dmra.pvvf@gnr.pt',
    'Posto Territorial de Vila Verde': 'ct.brg.dbrg.pvlv@gnr.pt',
    'Posto Territorial de Vila Viçosa': 'ct.evr.drgm.pvlv@gnr.pt',
    'Posto Territorial de Vila das Aves': 'ct.prt.dsts.pvla@gnr.pt',
    'Posto Territorial de Vila de Rei': 'ct.ctb.dsrt.pvlr@gnr.pt',
    'Posto Territorial de Vila do Bispo': 'ct.far.dptm.pvlb@gnr.pt',
    'Posto Territorial de Vila do Conde': 'ct.prt.dmts.pvlc@gnr.pt',
    'Posto Territorial de Vila do Porto (Santa Maria)': 'ct.acr.dpdl.pvlp@gnr.pt',
    'Posto Territorial de Vilamoura': 'ct.far.dlle.pvlm@gnr.pt',
    'Posto Territorial de Vilar Formoso': 'ct.grd.dvfm.pvfm@gnr.pt',
    'Posto Territorial de Vimieiro': 'ct.evr.detz.pvmr@gnr.pt',
    'Posto Territorial de Vimioso': 'ct.bgc.dmdr.pvms@gnr.pt',
    'Posto Territorial de Vinhais': 'ct.bgc.dbgc.pvnh@gnr.pt',
    'Posto Territorial de Viseu': 'ct.vis.dvis.pvis@gnr.pt',
    'Posto Territorial de Vizela': 'ct.brg.dgmr.pvzl@gnr.pt',
    'Posto Territorial de Vouzela': 'ct.vis.dvis.pvzl@gnr.pt',
    'Posto Territorial de Zebreira': 'ct.ctb.didn.pzbr@gnr.pt',
    'Posto Territorial de Águeda': 'ct.avr.dagd.pagd@gnr.pt',
    'Posto Territorial de Évora': 'ct.evr.devr.pevr@gnr.pt',
    'Posto Territorial de Ílhavo': 'ct.avr.davr.pilh@gnr.pt',
    'Posto Territorial de Óbidos': 'ct.lra.dclr.pobd@gnr.pt',
    'Posto Territorial do Corvo': 'ct.acr.dhrt.pcrv@gnr.pt',
    'Posto Territorial do Funchal': 'ct.mad.dfun.pfun@gnr.pt',
    'Posto de Trânsito de Chaves': 'ct.vrl.tvrl.tchv@gnr.pt',
    'Posto de Trânsito da Figueira da Foz (Mealhada)': 'ct.cbr.tcbr.tfgf@gnr.pt',
    'Posto de Trânsito de Abrantes': 'ct.str.tstr.tabt@gnr.pt',
    'Posto de Trânsito de Coina': 'ct.stb.tstb.tcoi@gnr.pt',
    'Posto de Trânsito de Estremoz': 'ct.evr.tevr.tetz@gnr.pt',
    'Posto de Trânsito de Fafe': 'ct.brg.tbrg.tfaf@gnr.pt',
    'Posto de Trânsito de Grândola': 'ct.stb.tstb.tgdl@gnr.pt',
    'Posto de Trânsito de Maia': 'ct.prt.tprt.tmai@gnr.pt',
    'Posto de Trânsito de Ourique': 'ct.bja.tbja.torq@gnr.pt',
    'Posto de Trânsito de Ponte de Lima': 'ct.vct.tvct.tpnl@gnr.pt',
    'Posto de Trânsito de Salvaterra de Magos': 'ct.str.tstr.tsmg@gnr.pt',
    'Posto de Trânsito de Santa Maria da Feira': 'ct.avr.tsjm.tsmf@gnr.pt',
    'Posto de Trânsito de Tavira': 'ct.far.tfar.ttvr@gnr.pt',
    'Posto de Trânsito de Vendas Novas': 'ct.evr.tevr.tvnd@gnr.pt',
    'Revista da Guarda': 'revista@gnr.pt',
    'Secretaria-Geral da Guarda': 'cg.sg@gnr.pt',
    'Sepna Ct Vila Real': 'ct.dvrl.npa@gnr.pt',
    'Serviço de Assistência Religiosa': 'cari.sar@gnr.pt',
    'Serviços Sociais da GNR': 'ssgnr@ssgnr.pt',
    'Subdestacamento Territorial de Quarteira': 'ct.far.dlle.pqrt@gnr.pt',
    'Subdestacamento Territorial de Alcabideche': 'ct.lsb.dsnt.sdacb@gnr.pt',
    'Subdestacamento Territorial de Fafe': 'ct.brg.dfaf.pfaf@gnr.pt',
    'Subdestacamento Territorial de Sintra': 'ct.lsb.dsnt.sdsnt@gnr.pt',
    'Subdestacamento de Controlo Costeiro da Figueira da Foz': 'ucc.dfgf.sdfgf@gnr.pt',
    'Subdestacamento de Controlo Costeiro da Fonte da Telha': 'ucc.dlsb.sdftt@gnr.pt',
    'Subdestacamento de Controlo Costeiro da Nazaré': 'ucc.dfgf.sdnzr@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Aljezur': 'ucc.dsin.sdajz@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Aveiro': 'ucc.dfgf.sdavr@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Caminha': 'ucc.dmts.sdcmn@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Esposende': 'ucc.dmts.sdesp@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Lisboa': 'ucc.dlsb.sdlsb@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Matosinhos': 'ucc.dmts.sdmts@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Olhão': 'ucc.dolh.sdolh@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Peniche': 'ucc.dlsb.sdpnc@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Portimão': 'ucc.dolh.sdptm@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Setúbal': 'ucc.dlsb.sdstb@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Sines': 'ucc.dsin.sdsin@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Vila Nova de Milfontes': 'ucc.dsin.sdvnm@gnr.pt',
    'Subdestacamento de Controlo Costeiro de Vila Real de St António': 'ucc.dolh.sdvra@gnr.pt',
    'Unidade Nacional de Trânsito': 'unt@gnr.pt',
    'Unidade de Apoio Geral': 'cari.uag@gnr.pt',
    'Unidade de Ação Fiscal': 'uaf@gnr.pt',
    'Unidade de Controlo Costeiro': 'ucc@gnr.pt',
    'Unidade de Intervenção': 'ui@gnr.pt',
    'Unidade de Segurança e Honras de Estado': 'ushe@gnr.pt'  
};
