const pm = {
    'Albufeira': 'geral@cm-albufeira.pt',
    'Amadora': 'policia.municipal@cm-amadora.pt',
    'Aveiro': 'policia.municipal@cm-aveiro.pt',
    'Braga': 'policia.municipal@cm-braga.pt',
    'Cabeceiras de Basto': 'policiamunicipal@cabeceirasdebasto.pt',
    'Cascais': 'policia.municipal@cm-cascais.pt',
    'Coimbra': 'policia.municipal@cm-coimbra.pt',
    'Fafe': 'pmfafe@sapo.pt',
    'Felgueiras': 'policia.municipal@cm-felgueiras.pt',
    'Gondomar': 'pmunicipal@cm-gondomar.pt',
    'Guimarães': 'policia.municipal@cm-guimaraes.pt',
    'Marco de Canaveses': 'policia.municipal@cm-marco-canavese.pt',
    'Mafra': 'policiamunicipal@cm-mafra.pt',
    'Maia': 'pm@cm-maia.pt',
    'Matosinhos': 'mail@cm-matosinhos.pt',
    'Lisboa': 'pm@cm-lisboa.pt',
    'Loures': 'policia_municipal@cm-loures.pt',
    'Oeiras': 'spm@cm-oeiras.pt',
    'Paredes': 'policiamunicipal@cm-paredes.pt',
    'Paços de Ferreira': 'policiamunicipalpfr@iol.pt',
    'Ponta Delgada': 'policiamunicipal@mpdelgada.pt',
    'Porto': 'policiamunicipal@cm-porto.pt',
    'Póvoa de Varzim': 'policiamunicipal@cm-pvarzim.pt',
    'Santo Tirso': 'pm@cm-stirso.pt',
    'Sintra': 'policiamunicipal@cm-sintra.pt',
    'Trofa': 'policia.municipal@mun-trofa.pt',
    'Vieira do Minho': 'pmvieiraminho@hotmail.com',
    'Vila do Conde': 'geral@viladoconde.pt',
    'Vila Nova de Famalicão': 'policiamunicipal@vilanovadefamalicao.org',
    'Vila Nova de Gaia': 'pm@cm-gaia.pt',
    'Vila Nova de Poiares': 'policiamunicipal@mail.telepac.pt',
    'Viseu': 'policia.municipal@cmviseu.pt'
};
