const psp = {
    'Divisão de Trânsito da PSP de Lisboa': 'dt.lisboa@psp.pt',
    '1.ª Divisão Policial - Porto': '1div.porto@psp.pt',
    '1.ª Divisão Policial Lisboa': '1div.lisboa@psp.pt',
    '1.ª Esquadra de Investigação Criminal': '1eic.lisboa@psp.pt',
    '1.ª Esquadra de Investigação Criminal - Porto': '1eic.porto@psp.pt',
    '3.ª Divisão Policial - Porto': '3div.porto@psp.pt',
    '3.ª Esquadra de Investigação Criminal - Porto': '3eic.porto@psp.pt',
    '4.ª Esquadra de Investigação Criminal - Porto': '4eic.porto@psp.pt',
    '5.ª Esquadra de Investigação Criminal - Porto': '5eic.porto@psp.pt',
    '6.ª Esquadra de Investigação Criminal - Porto': '6eic.porto@psp.pt',
    '7.ª Esquadra de Investigação Criminal - Porto': '7eic.porto@psp.pt',
    '8.ª Esquadra de Investigação Criminal - Porto': '8eic.porto@psp.pt',
    'Abrantes - Esquadra': 'stresqabt@psp.pt',
    'Afurada - Vila Nova de Gaia - Esquadra': 'afurada.porto@psp.pt',
    'Alcobaça - Esquadra': 'alcobaca.leiria@psp.pt',
    'Alhandra - Vila Franca de Xira - 92.ª Esquadra Lisboa': 'alhandra.lisboa@psp.pt',
    'Almada - Divisão Policial': 'divalmada.setubal@psp.pt',
    'Almada - Esquadra de Intervenção e Fiscalização Policial': 'divalmada.setubal@psp.pt',
    'Almada - Esquadra de Investigação Criminal': 'divalmada.setubal@psp.pt',
    'Almada - Esquadra de Trânsito': 'divalmada.setubal@psp.pt',
    'Alta de Lisboa - Trânsito - Esquadra Moto': 'esqmotodt.lisboa@psp.pt',
    'Alta de Lisboa - Trânsito - Esquadra de Fiscalização Tecnica': 'eftecnicadt.lisboa@psp.pt',
    'Alverca do Ribatejo - Vila Franca de Xira - 91.ª Esquadra Lisboa': 'alverca.lisboa@psp.pt',
    'Amadora - Divisão Policial': 'divamadora.lisboa@psp.pt',
    'Amadora - Esquadra de Intervenção e Fiscalização Policial': 'eicamadora.lisboa@psp.pt',
    'Amadora - Esquadra de Investigação Criminal': 'eicamadora.lisboa@psp.pt',
    'Angra do Heroismo - Divisão Policial': 'cpangra@psp.pt',
    'Aveiro - Comando Distrital': 'cpaveiro@psp.pt',
    'Aveiro - Esquadra de Trânsito': 'esqtr.aveiro@psp.pt',
    'Açores - Comando Regional': 'cracores@psp.pt',
    'Baixa da Banheira - Esquadra': 'baixadabanheira.setubal@psp.pt',
    'Barcelos - Esquadra': 'barcelos.braga@psp.pt',
    'Barreiro - 5.ª Esquadra': 'stb5esq@psp.pt',
    'Barreiro - Divisão Policial': 'noi.barreiro@psp.pt',
    'Barreiro - Esquadra de Intervenção e Fiscalização Policial': 'stbeifpbarreiro@psp.pt',
    'Barreiro - Esquadra de Investigação Criminal': 'eicbarreiro.setubal@psp.pt',
    'Barreiro - Esquadra de Trânsito': 'stbesqtrabrr@psp.pt',
    'Beja - Comando Distrital': 'cpbeja@psp.pt',
    'Beja - Esquadra': 'esquadrasede.beja@psp.pt',
    'Beja - Esquadra de Intervenção e Fiscalização Policial': 'eifp.beja@psp.pt',
    'Beja - Esquadra de Investigação Criminal': 'eic.beja@psp.pt',
    'Beja - Esquadra de Trânsito': 'etr.beja@psp.pt',
    'Bela Vista - Setúbal - 2.ª Esquadra': 'stb2esq@psp.pt',
    'Benfica - 3.ª Divisão Policial Lisboa': '3div.lisboa@psp.pt',
    'Benfica - 3.ª Esquadra de Investigação Criminal': '3eic.lisboa@psp.pt',
    'Braga - 1.ª Esquadra': 'brg1esq@psp.pt',
    'Braga - 2.ª Esquadra (Souto Mayor)': 'brg2esq@psp.pt',
    'Braga - Comando Distrital': 'cpbraga@psp.pt',
    'Braga - Divisão Policial': 'divbrg.braga@psp.pt',
    'Braga - Esquadra de Intervenção e Fiscalização Policial': 'eifp.braga@psp.pt',
    'Braga - Esquadra de Investigação Criminal': 'brgeic@psp.pt',
    'Braga - Esquadra de Trânsito (Souto Mayor)': 'brgesqtr@psp.pt',
    'Bragança - Comando Distrital': 'cpbraganca@psp.pt',
    'Bragança - Esquadra': 'bgcesqsede@psp.pt',
    'Bragança - Esquadra de Intervenção e Fiscalização': 'mailto:eic.braganca@psp.pt',
    'Bragança - Esquadra de Investigação Criminal': 'eic.braganca@psp.pt',
    'Brigada de Proteção Ambiental - Porto': 'bripa.porto@psp.pt',
    'Caldas da Rainha - Esquadra': 'caldasdarainha.leiria@psp.pt',
    'Calheta - Esquadra': 'madesqcalheta@psp.pt',
    'Calvario - 4.ª Esquadra de Investigação Criminal': '4eic.lisboa@psp.pt',
    'Calvário - 4.ª Divisão Policial Lisboa': '4div.lisboa@psp.pt',
    'Camacha - Posto de Polícia': 'madesqcamacha@psp.pt',
    'Canidelo - Vila Nova de Gaia - Esquadra': 'canidelo.porto@psp.pt',
    'Cartaxo - Esquadra': 'stresqctx@psp.pt',
    'Casal de Cambra - Sintra - 86.ª Esquadra Lisboa': 'casaldecambra.lisboa@psp.pt',
    'Cascais - Divisão Policial': 'divcascais.lisboa@psp.pt',
    'Cascais - Esquadra de Investigação Criminal': 'eiccascais.lisboa@psp.pt',
    'Cascais - Esquadra de Trânsito': 'div.cascais.lisboa@psp.pt',
    'Cascais - Esquadra de Turismo': 'lsbcscetur@psp.pt',
    'Castelo Branco - Comando Distrital': 'cpcbranco@psp.pt',
    'Castelo Branco - Esquadra': 'ctbesqsede@psp.pt',
    'Centro de Inativação de Explosivos e Segurança Em Subsolo': 'ciexss@psp.pt',
    'Chaves - Divisão Policial': 'vrlsecchv@psp.pt',
    'Chaves - Esquadra de Intervenção e Fiscalização Policial': 'vrlsecchv@psp.pt',
    'Chaves - Esquadra de Investigação Criminal': 'vrlsecchv@psp.pt',
    'Chaves - Esquadra de Trânsito': 'vrlsecchv@psp.pt',
    'Coimbra - 1.ª Esquadra': 'cbr1esq@psp.pt',
    'Coimbra - 2.ª Esquadra': 'cbr2esq@psp.pt',
    'Coimbra - Comando Distrital': 'cpcoimbra@psp.pt',
    'Corpo de Intervenção': 'ci@psp.pt',
    'Corpo de Segurança Pessoal': 'csp@psp.pt',
    'Corroios - Seixal - Esquadra': 'corroios.setubal@psp.pt',
    'Covilhã - Divisão Policial': 'covilha.castelobranco@psp.pt',
    'Covilhã - Esquadra': 'covilha.castelobranco@psp.pt',
    'Covilhã - Esquadra de Intervenção e Fiscalização': 'covilha.castelobranco@psp.pt',
    'Covilhã - Esquadra de Investigação Criminal': 'covilha.castelobranco@psp.pt',
    'Covilhã - Esquadra de Trânsito': 'covilha.castelobranco@psp.pt',
    'Cruz de Pau - Seixal - Esquadra': 'cruzdepau.setubal@psp.pt',
    'Custóias - Matosinhos - Esquadra': 'custoias.porto@psp.pt',
    'Câmara de Lobos - Esquadra': 'madesqcamlobos@psp.pt',
    'Direção Nacional da Polícia de Segurança Pública': 'contacto@psp.pt',
    'Direção Nacional da Psp - Departamento de Armas e Explosivos': 'depaex@psp.pt',
    'Direção Nacional da Psp - Recursos Humanos': 'deprh@psp.pt',
    'Direção Nacional da Psp - Relações Publicas': 'contacto@psp.pt',
    'Entroncamento - Esquadra': 'stresqent@psp.pt',
    'Ermesinde - Esquadra': 'ermezinde.porto@psp.pt',
    'Escola Pratica de Policia': 'epp@psp.pt',
    'Espinho - Divisão Policial': 'espinho.aveiro@psp.pt',
    'Espinho - Esquadra': 'espinho.aveiro@psp.pt',
    'Estoril - Cascais - 51.ª Esquadra Lisboa': 'esquadrasecxxi@psp.pt',
    'Estremoz - Esquadra': 'evresqetz@psp.pt',
    'Faro - Comando Distrital': 'cpfaro@psp.pt',
    'Faro - Divisão Policial': 'div.faro@psp.pt',
    'Figueira da Foz - Divisão Policial': 'figueiradafoz.coimbra@psp.pt',
    'Funchal - Esquadra': 'madesqfunchal@psp.pt',
    'Funchal - Esquadra de Trânsito': 'maddt@psp.pt',
    'Gondomar - Divisão Policial': 'divgondomar.porto@psp.pt',
    'Gondomar - Esquadra': 'gondomar.porto@psp.pt',
    'Gouveia - Esquadra': 'grdesqgva@psp.pt',
    'Grupo de Operações Especiais': 'goe@psp.pt',
    'Guarda - Comando Distrital': 'cpguarda@psp.pt',
    'Guarda - Esquadra': 'grdesqsede@psp.pt',
    'Guarda - Esquadra de Trânsito': 'grdesqtr@psp.pt',
    'Guimarães - Divisão Policial': 'guimaraes.braga@psp.pt',
    'Guimarães - Esquadra de Intervenção e Fiscalização Policial': 'eifpguim.braga@psp.pt',
    'Horta - Divisão Policial': 'cphorta@psp.pt',
    'Horta - Esquadra': 'hrtesqsede@psp.pt',
    'Horta - Esquadra de Intervenção e Fiscalização Policial': 'hrteir@psp.pt',
    'Horta - Esquadra de Investigação Criminal': 'hrteic@psp.pt',
    'Horta - Esquadra de Segurança Aeroportuaria': 'hrtsegaer@psp.pt',
    'Horta - Esquadra de Trânsito': 'hrtesqtr@psp.pt',
    'Instituto Superior de Ciências Policiais e Segurança Interna': 'iscpsi@psp.pt',
    'Lages do Pico - Esquadra': 'hrtlgp@psp.pt',
    'Lagos - Esquadra': 'lagos.faro@psp.pt',
    'Lajes das Flores - Esquadra': 'hrtlgf@psp.pt',
    'Lamego - Esquadra': 'vislmg@psp.pt',
    'Laranjeiro - Almada - Esquadra': 'laranjeiro.setubal@psp.pt',
    'Leiria - Comando Distrital': 'cpleiria@psp.pt',
    'Leiria - Esquadra': 'esquadrasede.leiria@psp.pt',
    'Lisboa - 6.ª Esquadra de Investigação Criminal': '6eic.lisboa@psp.pt',
    'Lisboa - 7.ª Esquadra de Investigação Criminal': '7eic.lisboa@psp.pt',
    'Lisboa - 8.ª Esquadra de Investigação Criminal': '8eic.lisboa@psp.pt',
    'Lisboa - Comando Metropolitano': 'cmlisboa@psp.pt',
    'Lisboa - Divisão de Investigação Criminal': 'dic.lisboa@psp.pt',
    'Lisboa - Divisão de Investigação Criminal': 'diceij.lisboa@psp.pt',
    'Lisboa - Divisão de Segurança A Instações': 'dsi.lisboa@psp.pt',
    'Lisboa - Divisão de Segurança Aeroportuaria': 'dsa.lisboa@psp.pt',
    'Lisboa - Divisão de Seguraça A Transportes Publicos': 'dstp.lisboa@psp.pt',
    'Loures - Divisão Policial': 'divloures.lisboa@psp.pt',
    'Machico - Esquadra': 'madesqmachico@psp.pt',
    'Madalena do Pico - Esquadra': 'hrtmdp@psp.pt',
    'Madeira - Comando Regional': 'crmadeira@psp.pt',
    'Madeira - Divisão de Segurança Aeroportuaria': 'madesegaer@psp.pt',
    'Madeira - Esquadra de Segurança Aeroportuaria': 'madesegaer@psp.pt',
    'Maia - Divisão Policial': 'divmaia.porto@psp.pt',
    'Maia - Esquadra': 'maia.porto@psp.pt',
    'Marinha Grande - Esquadra': 'marinhagrande.leiria@psp.pt',
    'Marrazes - Esquadra': 'marrazes.leiria@psp.pt',
    'Matosinhos - Divisão Policial': 'divmatosinhos.porto@psp.pt',
    'Mira-Sintra - Sintra - 87.ª Esquadra Lisboa': 'mirasintra.lisboa@psp.pt',
    'Mirandela - Esquadra': 'mirandela.braganca@psp.pt',
    'Montijo - Esquadra': 'montijo.setubal@psp.pt',
    'Moura - Esquadra': 'moura.beja@psp.pt',
    'Nazaré - Esquadra': 'nazare.leiria@psp.pt',
    'Oeiras - Divisão Policial': 'divoeiras.lisboa@psp.pt',
    'Oeiras - Esquadra de Intervenção e Fiscalização': 'divoeiras.lisboa@psp.pt',
    'Oeiras - Esquadra de Investigação Criminal': 'eicoeiras.lisboa@psp.pt',
    'Olhão - Esquadra': 'olhao.faro@psp.pt',
    'Olivais - 2.ª Esquadra de Investigação Criminal': '2eic.lisboa@psp.pt',
    'Olivais Sul - 2.ª Divisão Policial Lisboa': '2div.lisboa@psp.pt',
    'Oliveira do Douro - Vila Nova de Gaia - Esquadra': 'oliveiradodouro.porto@psp.pt',
    'Ourém - Esquadra': 'ourem.santarem@psp.pt',
    'Ovar - Esquadra': 'ovar.aveiro@psp.pt',
    'Parque de Viaturas Rebocadas - Campo Pequeno': 'cgrandedt.lisboa@psp.pt',
    'Parque de Viaturas Rebocadas - Restelo': 'restelodt.lisboa@psp.pt',
    'Penha de França - 5.ª Divisão Policial Lisboa': '5div.lisboa@psp.pt',
    'Penha de França - 5.ª Esquadra de Investigação Criminal': '5eic.lisboa@psp.pt',
    'Peniche - Esquadra': 'peniche.leiria@psp.pt',
    'Pombal - Esquadra': 'pombal.leiria@psp.pt',
    'Ponta Delgada - Divisão Policial': 'cppdelgada@psp.pt',
    'Ponta do Sol - Esquadra': 'madesqpsol@psp.pt',
    'Ponte de Lima - Esquadra': 'pontedelima.vcastelo@psp.pt',
    'Portalegre - Comando Distrital': 'cpportalegre@psp.pt',
    'Portalegre - Esquadra': 'ptgecg@psp.pt',
    'Portimão - Divisão Policial': 'divportimao.faro@psp.pt',
    'Portimão - Esquadra': 'divportimao.faro@psp.pt',
    'Portimão - Esquadra de Intervenção e Fiscalização Policial': 'divportimao.faro@psp.pt',
    'Portimão - Esquadra de Investigação Criminal': 'divportimao.faro@psp.pt',
    'Portimão - Esquadra de Trânsito': 'divportimao.faro@psp.pt',
    'Porto - Comando Metropolitano': 'cmporto@psp.pt',
    'Porto - Destacamento do Corpo de Intervenção': 'ci.porto@psp.pt',
    'Porto - Divisão de Investigação Criminal': 'dic.cmporto@psp.pt',
    'Porto - Divisão de Segurança Aeroportuaria': 'aeroporto.porto@psp.pt',
    'Porto - Divisão de Trânsito': 'prtdt@psp.pt',
    'Porto - Esquadra de Turismo': 'prtetur@psp.pt',
    'Porto - N?.?cleo de Segurança Privada': 'prtnspriv@psp.pt',
    'Porto Moniz - Esquadra': 'madesqpmoniz@psp.pt',
    'Porto Salvo - Oeiras - 82.ª Esquadra Lisboa': 'portosalvo.lisboa@psp.pt',
    'Porto Santo - Esquadra': 'madesqpsanto@psp.pt',
    'Porto Santo - Esquadra de Segurança Aeroportuaria': 'aeroporto.psanto@psp.pt',
    'Povoa de Varzim - Esquadra': 'povoavarzim.porto@psp.pt',
    'Pragal - Almada - Esquadra': 'pragal.setubal@psp.pt',
    'Queijas - Oeiras - 85.ª Esquadra Lisboa': 'queijas.lisboa@psp.pt',
    'Quinta da Lomba - Barreiro - Esquadra': 'stbpaqdl@psp.pt',
    'Quintanilha - Centro de Coordenação Policial e Aduaneira': 'ccpa.quintanilha@psp.pt',
    'Restauradores - Esquadra de Turismo1': 'lsbetur@psp.pt',
    'Ribeira Brava - Esquadra': 'madesqrbrava@psp.pt',
    'Rio Tinto - Gondomar - Esquadra': 'riotinto.porto@psp.pt',
    'Rio de Mouro - Sintra - 89.ª Esquadra Lisboa': 'riodemouro.lisboa@psp.pt',
    'Santa Apolónia - Esquadra de Turismo': 'lsbetur@psp.pt',
    'Santa Cruz - Esquadra': 'madesqscruz@psp.pt',
    'Santa Cruz das Flores - Esquadra': 'hrtscf@psp.pt',
    'Santa Cruz das Flores - Esquadra de Investigação Criminal': 'hrtscfsic@psp.pt',
    'Santa Maria da Feira - Esquadra': 'smfeira.aveiro@psp.pt',
    'Santana - Esquadra': 'madesqsantana@psp.pt',
    'Santarém - Comando Distrital': 'cdsantarem@psp.pt',
    'Santarém - Esquadra': 'stresqsede@psp.pt',
    'Santo Tirso - Esquadra': 'santotirso.porto@psp.pt',
    'Secção de Contra-Ordenações da Divisão de Trânsito': 'scr.dt.lisboa@psp.pt',
    'Seixal - Divisão Policial': 'divseixal.setubal@psp.pt',
    'Seixal - Esquadra': 'seixal.setubal@psp.pt',
    'Seixal - Esquadra de Intervenção e Fiscalização Policial': 'divseixal.setubal@psp.pt',
    'Seixal - Esquadra de Investigação Criminal': 'divseixal.setubal@psp.pt',
    'Setúbal - 1.ª Esquadra': 'stb1esq@psp.pt',
    'Setúbal - Comando Distrital': 'cpsetubal@psp.pt',
    'Setúbal - Divisão Policial': 'stbao.setubal@psp.pt',
    'Setúbal - Esquadra de Intervenção e Fiscalização Policial': 'stbeifp@psp.pt',
    'Setúbal - Esquadra de Investigação Criminal': 'stbao.setubal@psp.pt',
    'Setúbal - Esquadra de Trânsito': 'stbesqtr@psp.pt',
    'Sintra - Divisão Policial': 'sintra.lisboa@psp.pt',
    'São João da Madeira - Esquadra': 'sjmadeira.aveiro@psp.pt',
    'São Mamede de Infesta - Matosinhos - Esquadra': 'smamedeinfesta.porto@psp.pt',
    'São Roque do Pico - Esquadra': 'hrtesqsrp@psp.pt',
    'São Roque do Pico - Esquadra de Investigação Criminal': 'hrtsrpsic@psp.pt',
    'São Vicente - Esquadra': 'svicente.madeira@psp.pt',
    'Tavira - Esquadra': 'tavira.faro@psp.pt',
    'Tomar - Divisão Policial': 'strsectmr@psp.pt',
    'Torre da Marinha - Seixal - Posto de Atendimento': 'seixal.setubal@psp.pt',
    'Torres Novas - Esquadra': 'torresnovas.santarem@psp.pt',
    'Unidade Especial de Polícia': 'uep@psp.pt',
    'Valadares - Vila Nova de Gaia - Esquadra': 'valadares.porto@psp.pt',
    'Valbom - Gondomar - Esquadra': 'valbom.porto@psp.pt',
    'Valongo - Esquadra': 'valongo.porto@psp.pt',
    'Viana do Castelo - Comando Distrital': 'cpvcastelo@psp.pt',
    'Viana do Castelo - Esquadra': 'vctesqsede@psp.pt',
    'Vila Franca de Xira - Divisão Policial': 'vfxira.lisboa@psp.pt',
    'Vila Franca de Xira - Esq.ª de Intervenção e Fiscalização Policial': 'vfxira.lisboa@psp.pt',
    'Vila Franca de Xira - Esquadra de Investigação Criminal': 'vfxira.lisboa@psp.pt',
    'Vila Franca de Xira - Esquadra de Trânsito': 'vfxira.lisboa@psp.pt',
    'Vila Nova de Famalicão - Esquadra': 'famalicao.braga@psp.pt',
    'Vila Nova de Gaia - 10.ª Esquadra Porto': 'gaia.porto@psp.pt',
    'Vila Nova de Gaia - Divisão Policial': 'divvngaia.porto@psp.pt',
    'Vila Real - Comando Distrital': 'cpvreal@psp.pt',
    'Vila Real - Esquadra': 'vrlesqsede@psp.pt',
    'Vila Real de Santo Antonio - Esquadra': 'vrsa.faro@psp.pt',
    'Vila do Conde - Divisão Policial': 'divvconde.porto@psp.pt',
    'Vila do Conde - Esquadra': 'viladoconde@psp.pt',
    'Viseu - Comando Distrital': 'cpviseu@psp.pt',
    'Viseu - Esquadra': 'visesqsede@psp.pt',
    'Águas Santas - Maia - Esquadra': 'aguassantas.porto@psp.pt',
    'Évora - Comando Distrital': 'cpevora@psp.pt',
    'Évora - Esquadra de Intervenção e Fiscalização Policial': 'cpevora@psp.pt'
};
